# docker-compose.yml - Complete observability stack
services:
  # Jaeger - for traces
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"  # Jaeger UI
      - "14268:14268"  # HTTP collector for traces (traditional Jaeger format)
      - "14317:4317"   # OTLP gRPC receiver (host:container)
      - "14318:4318"   # OTLP HTTP receiver (host:container)
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - SPAN_STORAGE_TYPE=badger
      - BADGER_EPHEMERAL=false
      - BADGER_DIRECTORY_VALUE=/badger/data
      - BADGER_DIRECTORY_KEY=/badger/key
    volumes:
      - jaeger-badger:/badger
    user: "root"  # Fix permissions issue
  
  # Prometheus - for metrics
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"    # Prometheus UI
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=30d'
      - '--web.enable-lifecycle'
  
  # OTLP Collector - routes data to backends
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otelcol-contrib/otel-collector.yml"]
    volumes:
      - ./otel-collector.yml:/etc/otelcol-contrib/otel-collector.yml
    ports:
      - "4317:4317"    # OTLP gRPC receiver  
      - "4318:4318"    # OTLP HTTP receiver
    depends_on:
      - jaeger
      - prometheus
  
  # Grafana - for dashboards
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"    # Grafana UI
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage:
  jaeger-badger:
  prometheus-data:
