global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']  # Collector metrics endpoint
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']